CREATE TABLE dbo.AUTO_THOUGHTS (
	ID BIGINT IDENTITY(1,1) NOT NULL,
	SEVEN_COLUMNS_ID BIGINT NOT NULL,
	AUTO_THOUGHT NVARCHAR(500) NOT NULL,
	IS_MAIN BIT NOT NULL DEFAULT 0,
	CREATED_AT DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
	
	CONSTRAINT PK_AUTO_THOUGHTS
	PRIMARY KEY (ID),

	CONSTRAINT FK_AUTO_THOUGHTS_SEVEN_COLUMNS
	FOREIGN KEY (SEVEN_COLUMNS_ID)
	REFERENCES dbo.SEVEN_COLUMNS (ID)
);
GO