CREATE TABLE SEVEN_COLUMNS (
	ID BIGINT IDENTITY(1,1) NOT NULL,
	TITLE NVARCHAR(200) NOT NULL,
	IS_COMPLETE BIT NOT NULL,
	CREATED_DAY DATETIME2 NOT NULL,
	UPDATED_DAY DATETIME2 NOT NULL,
	IS_DELETE BIT NOT NULL,


	CONSTRAINT PK_SEVEN_COLUMNS
	PRIMARY KEY (ID)
);