CREATE TABLE dbo.SITUATIONS (
ID BIGINT IDENTITY(1,1) NOT NULL,
SEVEN_COLUMNS_ID BIGINT NOT NULL,

HAPPEND_TIME DATETIME2(0) NOT NULL,
HAPPEND_TIME_DETAIL NVARCHAR(100) NULL,

HAPPEND_PLACE NVARCHAR(100) NULL,


CHARACTER_FROM NVARCHAR(50) NULL,
CHARACTER_TO NVARCHAR(50) NULL,


PROPOSAL_OBJECT NVARCHAR(200) NOT NULL,
APPROACH NVARCHAR(200) NULL,

OTHER_INFO NVARCHAR(500) NULL,

CREATED_AT DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
UPDATED_AT DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),

CONSTRAINT PK_SITUATIONS
PRIMARY KEY (ID),


CONSTRAINT FK_SITUATIONS_SEVEN_COLUMNS
FOREIGN KEY (SEVEN_COLUMNS_ID)
REFERENCES dbo.SEVEN_COLUMNS(ID)
);