CREATE TABLE dbo.EMOTIONS (
	ID BIGINT IDENTITY(1,1) NOT NULL,
	THOUGHTS_ID BIGINT NOT NULL,
	EMOTION NVARCHAR(50) NOT NULL,
	POINT INT NOT NULL,
	CREATED_AT DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),

	CONSTRAINT PK_EMOTIONS
	PRIMARY KEY (ID),

	CONSTRAINT FK_EMOTIONS_AUTO_THOUGHTS
	FOREIGN KEY (THOUGHTS_ID)
	REFERENCES dbo.AUTO_THOUGHTS (ID),

	CONSTRAINT CK_EMOTIONS_POINT_RANGE
	CHECK (POINT BETWEEN 0 AND 100)
);
GO