select 
	t1.TITLE, t2.HAPPEND_TIME, t3.AUTO_THOUGHT, t4.EMOTION as AT_EMOTION, t4.POINT as AT_EMOTION_POINT
	, t5.CORE_BELIEF, t5.COUNTER_EVIDENCE
	, t6.BEFORE_THOUGHT, t6.CONJUNCTION_THOUGHT, t6.AFTER_THOUGHT
	, t7.EMOTION as ATV_EMOTION, t7.POINT as ATV_EMOTION_POINT
from 
	SEVEN_COLUMNS t1
inner join
	SITUATIONS t2
on
	t1.ID = t2.SEVEN_COLUMNS_ID
inner join
	AUTO_THOUGHTS t3
on
	t1.ID = t3.SEVEN_COLUMNS_ID
inner join
	AUTO_THOUGHT_EMOTIONS t4
on
	t3.ID = t4.AUTO_THOUGHTS_ID
inner join
	EVIDENCES t5
on
	t3.ID = t5.THOUGHTS_ID
inner join
	ADAPTIVE_THOUGHTS t6
on
	t3.ID = t6.THOUGHTS_ID
inner join
	ADAPTIVE_THOUGHT_EMOTIONS t7
on
	t6.ID = t7.ADAPTIVE_THOUGHTS_ID


--delete from SITUATIONS
--delete from EVIDENCES
--delete from AUTO_THOUGHT_EMOTIONS
--delete from ADAPTIVE_THOUGHT_EMOTIONS
--delete from ADAPTIVE_THOUGHTS
--delete from AUTO_THOUGHTS

--delete from SEVEN_COLUMNS