CREATE TABLE dbo.ADAPTIVE_THOUGHT_EMOTIONS (
	ID BIGINT IDENTITY(1,1) NOT NULL,
	ADAPTIVE_THOUGHTS_ID BIGINT NOT NULL,
	EMOTION NVARCHAR(50) NOT NULL,
	POINT INT NOT NULL,
	CREATED_AT DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),


	CONSTRAINT PK_ADAPTIVE_THOUGHT_EMOTIONS
	PRIMARY KEY (ID),


	CONSTRAINT FK_ADAPTIVE_THOUGHT_EMOTIONS_ADAPTIVE_THOUGHTS
	FOREIGN KEY (ADAPTIVE_THOUGHTS_ID)
	REFERENCES dbo.ADAPTIVE_THOUGHTS (ID),


	CONSTRAINT CK_ADAPTIVE_THOUGHT_EMOTIONS_POINT_RANGE
	CHECK (POINT BETWEEN 0 AND 100)
);
GO