CREATE TABLE dbo.ADAPTIVE_THOUGHTS (
	ID BIGINT IDENTITY(1,1) NOT NULL,
	THOUGHTS_ID BIGINT NOT NULL,
	BEFORE_THOUGHT NVARCHAR(500) NOT NULL,
	CONJUNCTION_THOUGHT NVARCHAR(50) NOT NULL,
	AFTER_THOUGHT NVARCHAR(500) NOT NULL,
	CREATED_AT DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),


	CONSTRAINT PK_ADAPTIVE_THOUGHTS
	PRIMARY KEY (ID),


	CONSTRAINT FK_ADAPTIVE_THOUGHTS_AUTO_THOUGHTS
	FOREIGN KEY (THOUGHTS_ID)
	REFERENCES dbo.AUTO_THOUGHTS (ID)
);
GO