CREATE TABLE dbo.AUTO_THOUGHT_EMOTIONS (
	ID BIGINT IDENTITY(1,1) NOT NULL,
	AUTO_THOUGHTS_ID BIGINT NOT NULL,
	EMOTION NVARCHAR(50) NOT NULL,
	POINT INT NOT NULL,
	CREATED_AT DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),

	CONSTRAINT PK_AUTO_THOUGHT_EMOTIONS
	PRIMARY KEY (ID),

	CONSTRAINT FK_AUTO_THOUGHT_EMOTIONS_AUTO_THOUGHTS
	FOREIGN KEY (AUTO_THOUGHTS_ID)
	REFERENCES dbo.AUTO_THOUGHTS (ID),

	CONSTRAINT CK_AUTO_THOUGHT_EMOTIONS_POINT_RANGE
	CHECK (POINT BETWEEN 0 AND 100)
);
GO