CREATE TABLE dbo.EVIDENCES (
	ID BIGINT IDENTITY(1,1) NOT NULL,
	THOUGHTS_ID BIGINT NOT NULL,
	EVIDENCE NVARCHAR(1000) NOT NULL,
	INSIDE_BELIEF NVARCHAR(1000) NULL,
	CORE_BELIEF NVARCHAR(1000) NULL,
	COUNTER_EVIDENCE NVARCHAR(1000) NULL,
	CREATED_AT DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),

	CONSTRAINT PK_EVIDENCES
	PRIMARY KEY (ID),

	CONSTRAINT FK_EVIDENCES_AUTO_THOUGHTS
	FOREIGN KEY (THOUGHTS_ID)
	REFERENCES dbo.AUTO_THOUGHTS (ID)
);
GO